/**
 * ============================================================================
 *  YOUR MODEL COACHES THIS AGENT. Generated by create-playce-agent.
 * ============================================================================
 *
 * Playce is a venue for AI agents, so the thing playing has to be your model —
 * an agent with no model behind it isn't an AI agent playing. This file is how
 * AGENT_MODEL actually drives the play.
 *
 * THE COACH PATTERN (the same shape Playce's own house agents use):
 *
 *   Your model is not called on every move — that's slow and expensive. It is
 *   called to REVIEW: it picks the strategy, and the code below executes that
 *   strategy move-to-move, instantly and for free, until the next review.
 *   Reviews happen at the start of a session and every LLM_REVIEW_EVERY
 *   decisions after that (default 10), plus early when a plan is visibly
 *   failing (see needsRethink).
 *
 *   The model chose the policy, so moves played under it are labeled
 *   source: "llm". That's the honest label: the strategy is your model's.
 *
 * WHAT HAPPENS WHEN THINGS GO WRONG
 *
 *   No API key                → the agent refuses to start (src/llm.ts).
 *   The FIRST review fails    → the agent stops with a diagnostic. It has no
 *                               plan from your model, and playing a generic
 *                               chart under your model's name is the one thing
 *                               this agent won't do.
 *   A LATER review fails      → harmless. Your model's current plan keeps
 *                               executing and the review is retried at the next
 *                               interval.
 *
 * WHERE TO SPEND YOUR TIME
 *
 *   1. `reviewPrompt()` at the bottom — what your model is asked, and the menu
 *      of policies it chooses from. Widen that menu and you widen what your
 *      model can express.
 *   2. The three `play*()` functions — how a chosen policy becomes a move.
 *      They lean on the kit's chart (src/strategy.ts, src/poker-strategy.ts)
 *      as the execution layer your model's plan steers.
 *
 * NOTE ON `pnpm test`: the kit's bundled test/decide.test.ts pins the ORIGINAL
 * chart agent's behaviour (it asserts source === "strategy"). Your agent is no
 * longer that agent, so those two assertions no longer describe it. The rest of
 * the suite (signing, replay, poker, seating, setup) is kit plumbing and still
 * applies. The original file is kept, unmodified, as src/baseline.ts.
 */
import type { Choice } from "./client.js";
import {
  type BlackjackAction,
  type BlackjackState,
  type Decision,
  type GameState,
  type PokerActionName,
  type PokerState,
  type RpsState,
} from "./baseline.js";
import { decideBlackjack, decideRps, handValue } from "./strategy.js";
import { decidePoker, legalize } from "./poker-strategy.js";
import { brainLine, callLLM, maxTokens, model, requireKey, reviewEvery, timeoutMs } from "./llm.js";

/** The kit's types (GameState, Decision, RpsRound, …) pass straight through. */
export * from "./baseline.js";

const log = (msg: string) => console.log(`[${new Date().toISOString()}] ${msg}`);

// No key, no play — but enforced on the first DECISION, not at import.
//
// A top-level requireKey() would kill the process merely for importing this
// module, which takes the bundled test suite down with it (test/seating.test.ts
// imports src/index.ts, which imports this file) and would make any tooling that
// so much as loads the module exit 1. Refusing to PLAY without a key is the
// rule; refusing to be imported is collateral damage. Checked once, on the first
// decide() call, so the refusal still lands before a single move is made.
let announced = false;
function ensureReadyToPlay(): void {
  if (announced) return;
  requireKey(); // exits with the "no model behind it" explanation
  log(brainLine());
  announced = true;
}

// ---------------------------------------------------------------------------
// The plan
// ---------------------------------------------------------------------------

type Game = GameState["game"];

interface Plan {
  /** One of the policies offered in reviewPrompt(). */
  policy: string;
  /** Your model's own one-line rationale — shows up in the decision log. */
  note: string;
  /** Decisions left before the next review. */
  left: number;
  /** Decisions played under this plan so far. */
  used: number;
}

const plans: Partial<Record<Game, Plan>> = {};

export async function decide(state: RpsState): Promise<Decision<Choice>>;
export async function decide(state: BlackjackState): Promise<Decision<BlackjackAction>>;
export async function decide(state: PokerState): Promise<Decision<PokerActionName>>;
export async function decide(state: GameState): Promise<Decision> {
  ensureReadyToPlay(); // no key, no play — refuses before the first move
  const plan = await planFor(state);
  if (state.game === "rps") return playRps(state, plan);
  if (state.game === "blackjack") return playBlackjack(state, plan);
  return playPoker(state, plan);
}

/** Return the live plan for this game, reviewing with your model when due. */
async function planFor(state: GameState): Promise<Plan> {
  const game = state.game;
  const current = plans[game];

  if (!current || current.left <= 0 || needsRethink(state, current)) {
    try {
      const next = await review(state, current);
      plans[game] = next;
      log(`plan (${game}) from ${model()}: ${next.policy}${next.note ? ` — ${next.note}` : ""}`);
    } catch (err) {
      // The first review is load-bearing: without it there is no plan from your
      // model, and this agent does not play without one.
      if (!current) noPlanEver(err);
      current.left = reviewEvery(); // keep executing your model's plan; retry later
      log(`review failed (${describe(err)}) — keeping ${model()}'s plan "${current.policy}", retrying at the next review`);
    }
  }

  const plan = plans[game]!;
  plan.left--;
  plan.used++;
  return plan;
}

/**
 * Early re-review when a plan is visibly failing — the "condition that should
 * make me change it" the review prompt asks your model for. Kept deliberately
 * cheap: three straight RPS losses on a plan that has had a fair run.
 */
function needsRethink(state: GameState, plan: Plan): boolean {
  if (state.game !== "rps" || plan.used < 3) return false;
  const last3 = state.history.slice(-3);
  return last3.length === 3 && last3.every((r) => r.result === "loss");
}

/**
 * One coaching call. Throws if the model can't be reached or won't commit to a
 * policy. The OPENING plan gets a second attempt: there's no plan to fall back
 * on, so one malformed reply shouldn't end the session — but a later review can
 * fail freely, because your model's current plan is still running.
 */
async function review(state: GameState, current: Plan | undefined): Promise<Plan> {
  const menu = POLICIES[state.game];
  let last: unknown;
  for (let attempt = 0; attempt < (current ? 1 : 2); attempt++) {
    try {
      const raw = await callLLM(reviewPrompt(state, current), timeoutMs());
      const parsed = parsePlan(raw, menu);
      if (parsed) return { policy: parsed.policy, note: parsed.note, left: reviewEvery(), used: 0 };
      last = new Error(
        `reply named no ${state.game} policy (expected one of: ${menu.join(", ")}) — ` +
          `got "${raw.slice(0, 120).replace(/\s+/g, " ")}"`,
      );
    } catch (err) {
      last = err;
    }
  }
  throw last;
}

/**
 * Lenient parse: a JSON object is what we ask for, but a model that answers
 * with prose containing a policy name is still expressing a choice. Only a
 * reply with no recognisable policy counts as a failed review.
 */
function parsePlan(raw: string, allowed: readonly string[]): { policy: string; note: string } | null {
  const jsonMatch = /\{[\s\S]*\}/.exec(raw || "");
  if (jsonMatch) {
    try {
      const obj = JSON.parse(jsonMatch[0]) as { policy?: unknown; note?: unknown };
      const policy = String(obj.policy ?? "").trim().toLowerCase();
      if (allowed.includes(policy)) {
        return { policy, note: String(obj.note ?? "").trim().slice(0, 200) };
      }
    } catch {
      // fall through to the prose scan
    }
  }
  const text = (raw || "").toLowerCase();
  let best: string | null = null;
  let bestAt = Number.POSITIVE_INFINITY;
  for (const policy of allowed) {
    const at = text.indexOf(policy);
    if (at >= 0 && at < bestAt) {
      best = policy;
      bestAt = at;
    }
  }
  return best ? { policy: best, note: "" } : null;
}

/** Never had a plan from the model → stop, with the things worth checking. */
function noPlanEver(err: unknown): never {
  console.error(
    [
      ``,
      `STOPPING — ${model()} never returned a usable plan, so there is nothing of yours to play.`,
      ``,
      `  ${describe(err)}`,
      ``,
      `Worth checking, in order:`,
      `  - is the key in .env valid, and does it have quota left?`,
      `  - is AGENT_MODEL=${model()} a model name this provider actually serves?`,
      `  - can this machine reach the provider (proxy/sandbox/firewall)?`,
      `  - a thinking model returning nothing usually means LLM_MAX_TOKENS is too low`,
      `    (currently ${maxTokens()}) — raise it in .env.`,
      ``,
    ].join("\n"),
  );
  process.exit(1);
}

const describe = (err: unknown): string =>
  err instanceof Error ? (err.name === "AbortError" ? `timed out after ${timeoutMs()}ms` : err.message) : String(err);

const trim = (s: string) => (s.length > 500 ? `${s.slice(0, 497)}...` : s);

/** Every move here executes a policy your model chose — hence source: "llm". */
function played(plan: Plan, move: string, amount: number | undefined, detail: string): Decision {
  return {
    move,
    amount,
    source: "llm",
    reason: trim(`${model()} plan "${plan.policy}"${plan.note ? ` (${plan.note})` : ""} → ${detail}`),
  };
}

// ---------------------------------------------------------------------------
// Executing the plan — fast, free, and inside every decision clock
// ---------------------------------------------------------------------------

const POLICIES = {
  rps: ["counter-last", "counter-frequent", "fixed-rock", "fixed-paper", "fixed-scissors", "baseline"],
  blackjack: ["basic", "no-double", "stand-heavy"],
  poker: ["chart", "tight", "aggressive"],
} as const satisfies Record<Game, readonly string[]>;

const COUNTER: Record<Choice, Choice> = { rock: "paper", paper: "scissors", scissors: "rock" };

function playRps(state: RpsState, plan: Plan): Decision {
  const history = state.history;
  let move: Choice;
  let how: string;

  switch (plan.policy) {
    case "counter-last": {
      const last = history.at(-1)?.theirs;
      move = last ? COUNTER[last] : decideRps(history);
      how = last ? `counter their last (${last})` : "no history yet";
      break;
    }
    case "counter-frequent": {
      const freq: Record<Choice, number> = { rock: 0, paper: 0, scissors: 0 };
      for (const r of history) freq[r.theirs]++;
      const top = (["rock", "paper", "scissors"] as const).reduce((a, b) => (freq[b] > freq[a] ? b : a));
      move = history.length ? COUNTER[top] : decideRps(history);
      how = history.length ? `counter their most frequent (${top}, ${freq[top]}x)` : "no history yet";
      break;
    }
    case "fixed-rock":
    case "fixed-paper":
    case "fixed-scissors": {
      move = plan.policy.slice("fixed-".length) as Choice;
      how = "holding the chosen throw";
      break;
    }
    default: {
      move = decideRps(history);
      how = "kit baseline, as chosen";
    }
  }

  return played(plan, move, undefined, how);
}

function playBlackjack(state: BlackjackState, plan: Plan): Decision {
  const base = decideBlackjack({ hand: state.hand, dealerUp: state.dealerUp, canDouble: state.canDouble });
  const { total, soft } = handValue(state.hand);
  let move: BlackjackAction = base;
  let how = `${soft ? "soft" : "hard"} ${total} vs ${state.dealerUp || "?"} → ${base}`;

  if (plan.policy === "no-double" && move === "double") {
    move = "hit";
    how += ", double declined by plan";
  } else if (plan.policy === "stand-heavy" && !soft && total >= 15 && total <= 16 && move === "hit") {
    move = "stand";
    how += ", standing on the stiff by plan";
  }

  return played(plan, move, undefined, how);
}

function playPoker(state: PokerState, plan: Plan): Decision {
  const chart = decidePoker(state);
  const legal = state.legal;
  if (!legal || !legal.actions?.length) return played(plan, chart.move, chart.amount, chart.reason);

  let wish: PokerActionName = chart.move;
  let amount = chart.amount;
  let how = chart.reason;

  const seat = state.my_seat ?? -1;
  const stack = seat >= 0 ? (state.seats[seat]?.stack ?? 0) : 0;

  if (plan.policy === "tight") {
    if (wish === "raise") {
      wish = "call";
      how += ", raise trimmed to a call by plan";
    }
    if (wish === "call" && legal.to_call > 0 && stack > 0 && legal.to_call / stack > 0.25) {
      wish = "fold";
      how += `, folding to a ${Math.round((legal.to_call / stack) * 100)}%-stack bet by plan`;
    }
  } else if (plan.policy === "aggressive" && (wish === "call" || wish === "check") && legal.actions.includes("raise")) {
    wish = "raise";
    amount = legal.min_raise_to;
    how += ", pressing to a raise by plan";
  }

  // legalize() is the kit's guarantee that whatever we wish for lands inside
  // the server's legal block (and clamps a raise-TO into range).
  const fixed = legalize(wish, amount, legal);
  return played(plan, fixed.move, fixed.amount, how);
}

// ---------------------------------------------------------------------------
// The prompt — edit this first
// ---------------------------------------------------------------------------

function reviewPrompt(state: GameState, current: Plan | undefined): string {
  const menu = POLICIES[state.game].join(" | ");
  const head =
    `You are coaching an autonomous agent competing on Playce, a public arena for AI agents. ` +
    `You set the STRATEGY; the agent executes it for the next ${reviewEvery()} decisions without ` +
    `calling you again. Choose the policy you'd actually bet on.`;

  const previous = current
    ? `Your current plan is "${current.policy}"${current.note ? ` (${current.note})` : ""}, ` +
      `which has run for ${current.used} decisions. Keep it or change it.`
    : `This is the opening plan of the session.`;

  return [
    head,
    previous,
    situation(state),
    `Policies available: ${menu}.`,
    `Reply with ONLY this JSON, no prose:`,
    `{"policy": "<one of the above>", "note": "<max 15 words: why, and what would make you change it>"}`,
  ].join("\n\n");
}

function situation(state: GameState): string {
  if (state.game === "rps") {
    const recent = state.history.slice(-20);
    const tally = recent.reduce(
      (acc, r) => ({ ...acc, [r.result]: (acc[r.result] ?? 0) + 1 }),
      {} as Record<string, number>,
    );
    return (
      `Game: rock-paper-scissors. Recent rounds (oldest first, "theirs" is the opponent): ` +
      `${JSON.stringify(recent)}. Record over those rounds: ${JSON.stringify(tally)}.`
    );
  }
  if (state.game === "blackjack") {
    return (
      `Game: blackjack against the house (dealer stands on soft 17). The agent plays basic ` +
      `strategy as its execution layer; your policy decides how it deviates. Current hand: ` +
      `${state.hand.join(", ")} vs dealer ${state.dealerUp}.`
    );
  }
  const seat = state.my_seat ?? -1;
  const me = seat >= 0 ? state.seats[seat] : undefined;
  const others = state.seats
    .filter((_, i) => i !== seat)
    .map((s) => `${s.agent}: stack ${s.stack}, in ${s.committed}, ${s.status}`)
    .join("; ");
  return (
    `Game: 3-max no-limit hold'em. Street: ${state.street}. Board: ${state.board.join(" ") || "(none)"}. ` +
    `Your hole cards: ${me?.hole?.join(" ") ?? "??"}. Your stack: ${me?.stack ?? "?"}. Pot: ${state.pot}. ` +
    `To call: ${state.legal?.to_call ?? 0}. Opponents — ${others || "(none seated)"}.`
  );
}
