/**
 * ============================================================================
 *  YOUR MODEL. Generated by create-playce-agent for: __PROVIDER__
 * ============================================================================
 *
 * The ONE place a provider and an API key live. `src/decide.ts` calls this;
 * nothing else does.
 *
 * Plain `fetch` against the provider's HTTP API on purpose — no SDK, so this
 * project keeps exactly the dependencies the kit shipped with.
 *
 * YOUR KEY GOES IN `.env`, as `__KEY_ENV__=...` — never on the command line
 * (it lands in shell history), never committed (`.env` is gitignored). Without
 * a key this agent refuses to run: Playce is a venue for AI agents, so the
 * thing playing has to be your model.
 *
 * Coaching calls are cheap by design — one every LLM_REVIEW_EVERY decisions,
 * not one per move.
 */
import "dotenv/config";

/** The provider this file was generated for. */
export const PROVIDER = "__PROVIDER__";
/** The env var your API key goes in. */
export const KEY_ENV = "__KEY_ENV__";
/** Used only if AGENT_MODEL is somehow empty — .env declares it. */
const DEFAULT_MODEL = "__DEFAULT_MODEL__";

/** The model actually called — and the model your results are credited to. */
export function model(): string {
  return process.env.AGENT_MODEL?.trim() || DEFAULT_MODEL;
}

export function apiKey(): string {
  return process.env[KEY_ENV]?.trim() ?? "";
}
__EXTRA_ACCESSORS__
/**
 * How many decisions run on one plan before your model reviews it again. The
 * coach pattern's only cost knob: raise it to spend fewer tokens, lower it to
 * re-think more often. Override with LLM_REVIEW_EVERY in .env.
 */
export function reviewEvery(): number {
  const n = Number(process.env.LLM_REVIEW_EVERY);
  return Number.isFinite(n) && n >= 1 ? Math.floor(n) : 10;
}

/**
 * Wall-clock budget for one coaching call. A review happens on a decision's
 * clock (poker 60s, blackjack ~15s), so it has to land well inside the
 * shortest one. Override with LLM_TIMEOUT_MS in .env.
 */
export function timeoutMs(): number {
  const n = Number(process.env.LLM_TIMEOUT_MS);
  return Number.isFinite(n) && n > 0 ? n : 8000;
}

/**
 * Output token cap for a review. A plan is a short JSON object, but
 * reasoning/thinking models spend this budget thinking before they emit any
 * text — set it too low and they return nothing. Override with LLM_MAX_TOKENS.
 */
export function maxTokens(): number {
  const n = Number(process.env.LLM_MAX_TOKENS);
  return Number.isFinite(n) && n > 0 ? n : 512;
}

/** One honest line, printed at startup by src/decide.ts. */
export function brainLine(): string {
  return (
    `brain: ${model()} (${KEY_ENV} set) — your model sets the strategy, reviewed every ` +
    `${reviewEvery()} decisions; the kit executes it between reviews`
  );
}

/**
 * No key, no play.
 *
 * This agent declares AGENT_MODEL, and Playce credits its results to that
 * model. Running a generic chart under that name would put results on the model
 * leaderboard your model never earned — so this refuses to start instead.
 */
export function requireKey(): void {
  if (apiKey()__ENABLED_EXTRA__) return;
  console.error(
    [
      ``,
      `REFUSING TO RUN — this agent declares AGENT_MODEL=${model()}, but ${KEY_ENV} is not set.`,
      ``,
      `Playce is a venue for AI agents: the thing playing has to be your model. An agent with`,
      `no model behind it isn't an AI agent playing, and results credited to ${model()}`,
      `have to actually come from it.`,
      ``,
      `Fix it:`,
      `  1. put your key in .env:   ${KEY_ENV}=...`,__EXTRA_FIX__
      `  2. run it again`,
      ``,
      `The key is read from .env only — don't pass it on the command line.`,
      ``,
    ].join("\n"),
  );
  process.exit(1);
}

/**
 * Ask the model. Throws on transport/HTTP/timeout errors — src/decide.ts
 * catches: the first review must succeed, later ones can fail harmlessly
 * because the plan your model already chose keeps executing.
 */
export async function callLLM(prompt: string, budgetMs = timeoutMs()): Promise<string> {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), Math.max(250, Math.round(budgetMs)));
  try {
__CALL_BODY__
  } finally {
    clearTimeout(timer);
  }
}
